#!/usr/bin/env python3
"""Cross-repo structural ontology aggregator (main#856, #820 C×T2 Task-3b).

The C×T2 topology is a **distributed per-repo generated structural index** plus a
**central semantic overlay/aggregator** in ``noorinalabs-main``. Each repo commits its
own ``ontology/structural/code-graph.json`` (generated by ``ontology_gen`` — #855). This
module rolls those per-repo indices up into a single **cross-repo view** under
``ontology/structural/`` in main, borrowing graphify's ``merge-graphs`` design:

* **union** of every in-scope repo's nodes and edges,
* **namespaced by repo** so ids never collide across repos — every node id / path and
  every edge endpoint is prefixed ``<repo>/`` (e.g. ``isnad-graph/src/api/app.py`` and
  ``isnad-graph/src/api/app.py::create_app``). The repo name becomes a virtual top-level
  directory, so the same relative path in two repos yields two distinct nodes.

It is **offline and deterministic** — no DB, no LLM, no network. It reads whatever
in-scope repo indices are present on disk and **degrades gracefully** when one is absent
(a repo whose index has not been generated/committed yet is simply skipped and reported).
Output is the same ``{"nodes": [...], "edges": [...]}`` document shape as a per-repo index,
serialized through the canonical :func:`~ontology_gen.model.serialize_graph` (one record
per line) so it is record-granular-diffable and union-mergeable by the same merge-driver.

CLI: ``python3 -m ontology_gen.aggregate <main-root> --out <central-graph.json>``
(default out: ``ontology/structural/cross-repo-graph.json``).
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

from .model import CodeGraph, Edge, GraphDict, Node, serialize_graph

# Short namespace -> repo directory relative to the noorinalabs-main root. The short
# names match the overlay's repo vocabulary (domain.yaml ``repos: [isnad-graph, ...]``).
# Child repos are cloned beneath the parent root (CLAUDE.md § Repository Map); "main" is
# the parent itself (".") so its own index is rolled in alongside the children.
DEFAULT_REPOS: dict[str, str] = {
    "main": ".",
    "isnad-graph": "noorinalabs-isnad-graph",
    "user-service": "noorinalabs-user-service",
    "deploy": "noorinalabs-deploy",
    "design-system": "noorinalabs-design-system",
    "data-acquisition": "noorinalabs-data-acquisition",
    "isnad-ingest-platform": "noorinalabs-isnad-ingest-platform",
    "landing-page": "noorinalabs-landing-page",
}

# Where each repo's generated per-repo index lives (relative to that repo's root).
INDEX_RELPATH = "ontology/structural/code-graph.json"
# Default central artifact path (relative to the main root).
DEFAULT_OUT = "ontology/structural/cross-repo-graph.json"


@dataclass(frozen=True)
class RepoIndexStatus:
    """Per-repo aggregation outcome — whether its index was found and what it contributed.

    ``nodes``/``edges`` are this repo's pre-dedup contribution (post-namespacing); the
    aggregated totals after cross-repo dedup come from the assembled graph, not the sum
    of these (a per-repo index never shares ids with another once namespaced, so in
    practice the totals equal the sums — but the graph remains the source of truth).
    """

    name: str
    index_path: Path
    present: bool
    nodes: int
    edges: int


def _load_namespaced(name: str, path: Path) -> tuple[list[Node], list[Edge]] | None:
    """Load one repo's ``code-graph.json`` and namespace every id by ``<name>/``.

    Returns ``None`` when the index is absent or unreadable (the caller degrades
    gracefully); returns ``([], [])`` for a present-but-empty index. Malformed records
    are skipped individually rather than aborting the whole roll-up.
    """
    try:
        with path.open(encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    raw_nodes = data.get("nodes", [])
    raw_edges = data.get("edges", [])
    if not isinstance(raw_nodes, list) or not isinstance(raw_edges, list):
        return None

    prefix = f"{name}/"
    nodes = [
        Node(
            id=prefix + str(n["id"]),
            kind=str(n["kind"]),
            path=prefix + str(n["path"]),
            line=int(n["line"]),
            lang=str(n["lang"]),
        )
        for n in raw_nodes
        if isinstance(n, dict) and {"id", "kind", "path", "line", "lang"} <= n.keys()
    ]
    edges = [
        Edge(src=prefix + str(e["src"]), dst=prefix + str(e["dst"]), type=str(e["type"]))
        for e in raw_edges
        if isinstance(e, dict) and {"src", "dst", "type"} <= e.keys()
    ]
    return nodes, edges


def aggregate(
    main_root: Path,
    repos: dict[str, str] | None = None,
) -> tuple[GraphDict, list[RepoIndexStatus]]:
    """Union every in-scope repo's structural index into one namespaced cross-repo graph.

    ``repos`` maps short namespace -> repo subdir (relative to ``main_root``); defaults to
    :data:`DEFAULT_REPOS`. Returns the canonical (deduped, sorted) graph dict and a status
    per repo (sorted by name for deterministic reporting).
    """
    repo_map = repos if repos is not None else DEFAULT_REPOS
    graph = CodeGraph()
    statuses: list[RepoIndexStatus] = []
    for name in sorted(repo_map):
        index_path = (main_root / repo_map[name] / INDEX_RELPATH).resolve()
        loaded = _load_namespaced(name, index_path)
        if loaded is None:
            statuses.append(RepoIndexStatus(name, index_path, False, 0, 0))
            continue
        nodes, edges = loaded
        graph.nodes.extend(nodes)
        graph.edges.extend(edges)
        statuses.append(RepoIndexStatus(name, index_path, True, len(nodes), len(edges)))
    return graph.to_dict(), statuses


def write_aggregate(
    main_root: Path,
    out_path: Path,
    repos: dict[str, str] | None = None,
) -> tuple[int, int, list[RepoIndexStatus]]:
    """Aggregate and write the central artifact. Returns ``(nodes, edges, statuses)``."""
    graph_dict, statuses = aggregate(main_root, repos)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(serialize_graph(graph_dict), encoding="utf-8")
    return len(graph_dict["nodes"]), len(graph_dict["edges"]), statuses


def _parse_repo_overrides(values: list[str]) -> dict[str, str]:
    overrides: dict[str, str] = {}
    for value in values:
        if "=" not in value:
            raise SystemExit(f"error: --repo expects NAME=SUBDIR, got: {value!r}")
        name, _, subdir = value.partition("=")
        if not name or not subdir:
            raise SystemExit(f"error: --repo expects NAME=SUBDIR, got: {value!r}")
        overrides[name] = subdir
    return overrides


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python3 -m ontology_gen.aggregate",
        description=(
            "Roll each in-scope repo's structural index (ontology/structural/code-graph.json) "
            "into a central, namespaced cross-repo graph under noorinalabs-main."
        ),
    )
    parser.add_argument(
        "main_root",
        nargs="?",
        default=".",
        help="Path to the noorinalabs-main root (default: current directory).",
    )
    parser.add_argument(
        "--out",
        default=DEFAULT_OUT,
        help=f"Output path for the cross-repo graph (default: {DEFAULT_OUT}).",
    )
    parser.add_argument(
        "--repo",
        action="append",
        default=[],
        metavar="NAME=SUBDIR",
        help=(
            "Override the in-scope repo set with an explicit NAME=SUBDIR entry "
            "(repeatable). When given, replaces the default repo map entirely."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    main_root = Path(args.main_root).resolve()
    if not main_root.is_dir():
        sys.stderr.write(f"error: main-root is not a directory: {main_root}\n")
        return 2

    repos = _parse_repo_overrides(args.repo) if args.repo else None
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = main_root / out_path

    nodes, edges, statuses = write_aggregate(main_root, out_path, repos)

    present = [s for s in statuses if s.present]
    absent = [s for s in statuses if not s.present]
    sys.stderr.write(
        f"ontology_gen.aggregate: {out_path} "
        f"(repos={len(present)}/{len(statuses)} nodes={nodes} edges={edges})\n"
    )
    for status in present:
        sys.stderr.write(f"  + {status.name}: nodes={status.nodes} edges={status.edges}\n")
    for status in absent:
        sys.stderr.write(f"  - {status.name}: index absent ({status.index_path}) — skipped\n")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
