#!/usr/bin/env python3
"""PostToolUse hook: Ontology change tracker.

Input: PostToolUse JSON on Edit / Write (the matchers actually wired in
``.claude/settings.json``). Computes SHA256 of the modified file and
updates ``ontology/checksums.json`` with the new hash in
``last_tracked``. When ``last_tracked != last_resolved``, the file is
"dirty" and needs ontology resolution.

Handles files across all child repos under the main repo root.

Path filtering (issue #143):
  Some edits target paths that are out of scope for the ontology —
  recording them inflates the dirty-file count without representing real
  drift. The hook therefore skips:

    * Substring SKIP_PATTERNS (e.g. ``__pycache__/``, ``.git/``).
    * Paths beginning with ``/tmp/`` — ephemeral scratch (e.g. issue-body
      staging files).
    * Paths under any ``.worktrees`` directory — ephemeral worktree copies.
      Two conventions are both gitignored (#523) and both skipped: the
      historical ``.claude/worktrees/`` path and the top-level
      ``.worktrees/`` path used by current wave/agent isolation. A worktree
      path enters this hook when an Edit/Write happens inside a worktree and
      the hook (anchored on the orchestrator cwd) records the worktree-
      relative path — e.g. ``.worktrees/deploy-0348-aisha/...`` or a
      child-repo file seen through a sibling worktree. These never resolve
      (``last_resolved: ""``) and once aborted a ``git merge --ff-only``
      during W11 close-out (#525). The canonical entry for the underlying
      file is updated whenever the file is next Edit/Written directly on the
      main checkout (this is a PostToolUse hook on tool calls, NOT a git
      post-merge hook, so a squash-merge of a worktree-only PR does not by
      itself update the tracker — the next direct Edit on main does).
      Skipping worktree paths is still the right call: it prevents
      accumulation of stale paths in ``checksums.json`` after worktrees are
      removed, and the slight latency in the canonical entry's
      ``last_tracked`` is acceptable noise-vs-signal trade.
    * Paths outside the repo tree — anything not under ``REPO_ROOT`` after
      resolution (e.g. user auto-memory files at
      ``/home/.../.claude/projects/.../memory/*.md``). The ontology only
      describes this repo; out-of-tree files cannot be its source of
      truth. (Note: on macOS, ``/tmp`` is a symlink to ``/private/tmp``;
      the SKIP_PREFIXES check uses the resolved path so the filter still
      catches it.)

Input Language:
  Fires on:      PostToolUse Edit, Write
  Matches:       Edit/Write whose `file_path` is non-empty AND resides inside
                 REPO_ROOT AND does NOT trip _should_skip (worktree-copy,
                 __pycache__, node_modules, /tmp/, etc.)
  Does NOT match: any other tool, missing file_path, paths under skip-
                  patterns, out-of-repo paths
  Flag pass-through: stdin JSON is forwarded verbatim to `check()` by the
                     PostToolUse dispatcher (`post_dispatcher.py`)

Exit codes:
  0 — always (advisory hook, never blocks)
"""

import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CHECKSUMS_FILE = REPO_ROOT / "ontology" / "checksums.json"

# Substring patterns: skip if any appears anywhere in the file path.
SKIP_PATTERNS = [
    "ontology/checksums.json",  # Don't track ourselves
    "ontology/structural/",  # GENERATED structural layer — see note below (#857)
    ".claude/annunaki/errors.jsonl",
    "__pycache__/",
    ".pyc",
    "node_modules/",
    ".git/",
    ".DS_Store",
    ".claude/worktrees/",  # Ephemeral worktree copies — see module docstring
]

# Tracker/resolver scope = the hand-curated SEMANTIC OVERLAY only (#857, #820/C×T2).
#   The change-tracker hook + `/ontology-rebuild` resolver exist to keep
#   *hand-maintained* ontology files in sync on every edit. As of #857 the
#   **structural** layer at ``ontology/structural/`` is GENERATED by an owned
#   generator (#855), not hand-resolved — it is always-current-by-regeneration.
#   Checksum dirty-tracking it would be meaningless churn (the generator rewrites
#   it wholesale), and ``/ontology-rebuild`` has nothing to resolve there. So
#   ``ontology/structural/`` is skipped here, exactly like ``checksums.json``
#   skips itself. The semantic overlay (``ontology/domain.yaml``,
#   ``ontology/services.yaml``, ``ontology/conventions.md``,
#   ``ontology/repos/*.yaml``, and other hand-edited ``*.md``) IS still tracked.

# Path prefixes: skip if the resolved file path starts with any of these.
SKIP_PREFIXES = ("/tmp/",)

# Directory names that mark a worktree-isolation tree. Any path with one of
# these as a path COMPONENT is an ephemeral worktree copy and must not be
# tracked into the parent checksums (#523 gitignored both; #525). Segment
# matching (not substring) so a legitimate file like ``notes.worktrees.md``
# is not skipped, while ``.worktrees/deploy-0348/x`` and
# ``.claude/worktrees/foo/x`` both are.
WORKTREE_DIR_NAMES = frozenset({".worktrees", "worktrees"})


def _is_worktree_path(file_path: str) -> bool:
    """True if any path component marks a worktree-isolation tree.

    Checks the raw path components (both the as-given and, when it differs,
    the resolved form) so that a relative worktree path recorded under the
    orchestrator cwd (``.worktrees/...``) is caught even before resolution.
    The ``worktrees`` bare name is only treated as a marker when its parent
    component is ``.claude`` — i.e. the historical ``.claude/worktrees/``
    convention — to avoid skipping an unrelated dir merely named
    ``worktrees``.
    """
    parts = Path(file_path).parts
    for i, part in enumerate(parts):
        if part == ".worktrees":
            return True
        if part == "worktrees" and i > 0 and parts[i - 1] == ".claude":
            return True
    return False


def _should_skip(file_path: str) -> bool:
    """Return True if this file should not be tracked.

    Filters in order: substring patterns, worktree path components, /tmp/
    prefix, then out-of-repo paths. See module docstring for the rationale
    behind each rule.
    """
    for pattern in SKIP_PATTERNS:
        if pattern in file_path:
            return True

    if _is_worktree_path(file_path):
        return True

    try:
        resolved = Path(file_path).resolve()
    except (OSError, RuntimeError):
        # Cannot resolve (e.g. broken symlink) — be conservative and skip.
        return True

    resolved_str = str(resolved)
    for prefix in SKIP_PREFIXES:
        if resolved_str.startswith(prefix):
            return True

    try:
        resolved.relative_to(REPO_ROOT)
    except ValueError:
        return True

    return False


def _compute_sha256(file_path: Path) -> str | None:
    """Compute SHA256 hash of a file. Returns None if file doesn't exist."""
    try:
        h = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        return h.hexdigest()
    except (OSError, PermissionError):
        return None


def _relative_path(file_path: str) -> str:
    """Convert absolute path to relative from repo root."""
    try:
        return str(Path(file_path).resolve().relative_to(REPO_ROOT))
    except ValueError:
        # File is outside repo root — use absolute path as key
        return file_path


def check(input_data: dict) -> dict | None:
    """Dispatcher-compatible entry point for PostToolUse Edit/Write.

    Returns None when the hook is not applicable (wrong tool, skip-path,
    unreadable file); returns an advisory dict describing the checksum
    update when an entry is written. The dispatcher treats non-None as
    advisory only.
    """
    tool_name = input_data.get("tool_name", "")
    if tool_name not in ("Edit", "Write"):
        return None

    file_path = input_data.get("tool_input", {}).get("file_path", "")
    if not file_path:
        return None

    if _should_skip(file_path):
        return None

    sha = _compute_sha256(Path(file_path))
    if sha is None:
        return None

    rel_path = _relative_path(file_path)
    now = datetime.now(timezone.utc).isoformat()

    try:
        with open(CHECKSUMS_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        data = {"version": 1, "files": {}}

    files = data.setdefault("files", {})

    existing = files.get(rel_path, {})
    files[rel_path] = {
        "last_tracked": sha,
        "last_resolved": existing.get("last_resolved", ""),
        "tracked_at": now,
        "resolved_at": existing.get("resolved_at", ""),
    }

    try:
        CHECKSUMS_FILE.parent.mkdir(parents=True, exist_ok=True)
        tmp = CHECKSUMS_FILE.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        tmp.replace(CHECKSUMS_FILE)
    except OSError:
        pass  # Never fail the hook

    return {"action": "tracked", "path": rel_path}


def main() -> None:
    try:
        input_data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)
    check(input_data)
    sys.exit(0)


if __name__ == "__main__":
    main()
